# Generated by Django 3.1.4 on 2020-12-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('about', models.TextField()),
                ('cost_to_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_to_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_num', models.CharField(max_length=150)),
                ('client_fio', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MachineList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_or_day', models.CharField(choices=[('HOUR', 'hour'), ('DAY', 'day')], max_length=150)),
                ('duration', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park_manage.machine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='park_manage.order')),
            ],
        ),
    ]
