# Generated by Django 3.1.4 on 2020-12-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('FREE', 'free'), ('NOT_FREE', 'busy'), ('REPAIR', 'on repair')], max_length=150),
        ),
    ]
