# Generated by Django 3.1.4 on 2020-12-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_manage', '0002_auto_20201202_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelist',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
